# Generated by Django 5.2.5 on 2025-08-31 19:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SentEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=255, verbose_name="موضوع")),
                ("body", models.TextField(verbose_name="متن ایمیل")),
                (
                    "from_email",
                    models.EmailField(max_length=254, verbose_name="از ایمیل"),
                ),
                ("recipients", models.TextField(verbose_name="گیرندگان")),
                (
                    "date_sent",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ارسال"),
                ),
            ],
            options={
                "verbose_name": "ایمیل ارسال شده",
                "verbose_name_plural": "ایمیل\u200cهای ارسال شده",
                "ordering": ["-date_sent"],
            },
        ),
    ]
