# Generated by Django 5.2.5 on 2025-08-31 21:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_sentemail"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="نام")),
                ("email", models.EmailField(max_length=254, verbose_name="ایمیل")),
                ("subject", models.CharField(max_length=200, verbose_name="موضوع")),
                ("message", models.TextField(verbose_name="پیام")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ارسال"),
                ),
                (
                    "is_read",
                    models.BooleanField(default=False, verbose_name="خوانده شده"),
                ),
            ],
            options={
                "verbose_name": "فرم تماس",
                "verbose_name_plural": "فرم\u200cهای تماس",
                "ordering": ["-created_at"],
            },
        ),
    ]
